"""Paket tournament."""
from .analysis import SchemeReport, analyze_existing, build_report
from .bracket import render_bracket, render_fairness, render_schedule
from .comparison import compare_reports, render_comparison
from .cross_event import detect_cross_event_conflicts, total_load_across_events
from .fairness import (
    FairnessReport,
    RestReport,
    analyze_rest,
    analyze_scheme,
    detect_internal_conflict,
    infer_bye_details,
)
from .generator import generate_scheme
from .generator_group import (
    auto_group_count,
    generate_group,
    generate_group_knockout,
    split_groups,
)
from .generator_knockout import (
    generate_knockout,
    generate_preliminary_knockout,
    next_pow2,
)
from .generator_roundrobin import generate_round_robin
from .models import (
    LOSER_PREFIX,
    QUALIFIER_PREFIX,
    RANK_QUALIFIER_PREFIX,
    ROUND_ORDER,
    VALID_FORMATS,
    ByeDetail,
    ClassInfo,
    Match,
    Result,
    ScheduledMatch,
    Scheme,
    Tournament,
    is_placeholder,
    minutes_to_hhmm,
    parse_group_qualifier,
    round_sort_key,
)
from .manual import move_match, replace_participant, set_walkover, swap_slots
from .multi import k_shift_of, optimize_multi_event, shift_report
from .probability import (
    MonteCarloResult,
    StrengthModel,
    custom_model,
    equal_model,
    exact_equal_title_probability,
    monte_carlo,
    percent_model,
    render_probability,
    simulate_once,
    win_probability,
)
from .registry import ClassRegistry, build_default_master, select_participants
from .results import (
    Results,
    StandRow,
    advance_scheme,
    build_standings,
    clear_result,
    record_result,
    render_standings,
)
from .scheduler import schedule_advanced, schedule_matches
from .whatif import apply_changes, what_if

__all__ = [
    "LOSER_PREFIX",
    "QUALIFIER_PREFIX",
    "RANK_QUALIFIER_PREFIX",
    "ROUND_ORDER",
    "VALID_FORMATS",
    "ByeDetail",
    "ClassInfo",
    "ClassRegistry",
    "FairnessReport",
    "Match",
    "MonteCarloResult",
    "RestReport",
    "Result",
    "Results",
    "ScheduledMatch",
    "Scheme",
    "SchemeReport",
    "StandRow",
    "StrengthModel",
    "Tournament",
    "advance_scheme",
    "analyze_existing",
    "analyze_rest",
    "analyze_scheme",
    "apply_changes",
    "auto_group_count",
    "build_default_master",
    "build_report",
    "build_standings",
    "clear_result",
    "compare_reports",
    "custom_model",
    "detect_cross_event_conflicts",
    "detect_internal_conflict",
    "equal_model",
    "exact_equal_title_probability",
    "generate_group",
    "generate_group_knockout",
    "generate_knockout",
    "generate_preliminary_knockout",
    "generate_round_robin",
    "generate_scheme",
    "infer_bye_details",
    "is_placeholder",
    "k_shift_of",
    "minutes_to_hhmm",
    "monte_carlo",
    "move_match",
    "next_pow2",
    "optimize_multi_event",
    "parse_group_qualifier",
    "percent_model",
    "record_result",
    "render_bracket",
    "render_comparison",
    "render_fairness",
    "render_probability",
    "render_schedule",
    "render_standings",
    "replace_participant",
    "round_sort_key",
    "schedule_advanced",
    "schedule_matches",
    "select_participants",
    "set_walkover",
    "shift_report",
    "simulate_once",
    "split_groups",
    "swap_slots",
    "total_load_across_events",
    "what_if",
    "win_probability",
]
